import { NextResponse } from "next/server";
import { getDb } from "../../lib/db";
import { getSession } from "../../lib/auth";

const MISSIONS:Record<string,any[]>={
"Data Analyst":[{id:"sales-dashboard",title:"E-commerce Sales Intelligence",description:"Build an executive dashboard from transaction data.",skills:["SQL","Power BI","Data Visualization"],difficulty:"Intermediate",hours:"5–7h",outcome:"Portfolio-ready dashboard",milestones:["Clean dataset","Write SQL analysis","Build dashboard","Write insights","Package project"]},{id:"retention-analysis",title:"Customer Retention Analysis",description:"Analyze customer behavior and retention patterns.",skills:["SQL","Python","Statistics"],difficulty:"Intermediate",hours:"5–7h",outcome:"Reproducible analysis",milestones:["Prepare data","Define metrics","Analyze cohorts","Visualize findings","Write recommendations"]}],
"Business Analyst":[{id:"ops-dashboard",title:"Operations Performance Dashboard",description:"Translate operational data into KPIs and bottlenecks.",skills:["Excel","Power BI","Business Analysis"],difficulty:"Intermediate",hours:"4–6h",outcome:"Executive KPI dashboard",milestones:["Define questions","Clean data","Build KPI model","Create dashboard","Present recommendations"]}],
"Product Analyst":[{id:"product-funnel",title:"Product Funnel & Conversion Analysis",description:"Analyze a product funnel and propose measurable experiments.",skills:["SQL","Product Analytics","Data Visualization"],difficulty:"Intermediate",hours:"5–7h",outcome:"Product analytics case study",milestones:["Map funnel","Calculate conversion","Find drop-offs","Visualize journey","Propose experiments"]}],
"Data Scientist":[{id:"churn-model",title:"Customer Churn Prediction",description:"Build an end-to-end supervised learning project.",skills:["Python","Statistics","Machine Learning"],difficulty:"Advanced",hours:"8–12h",outcome:"Reproducible ML project",milestones:["Explore dataset","Engineer features","Train baseline","Evaluate models","Explain impact"]}]
};
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:"Authentication required."},{status:401});const db=getDb();if(!db)return NextResponse.json({error:"Database unavailable."},{status:503});try{const p=await db.query("select target_role from career_profiles where user_id=$1",[s.userId]);const role=p.rows[0]?.target_role||"";const missions=MISSIONS[role]||[];const rows=await db.query("select id,project_key,title,status,milestones,evidence,created_at,updated_at from user_projects where user_id=$1 order by created_at desc",[s.userId]);return NextResponse.json({targetRole:role,missions,user_projects:rows.rows});}catch{return NextResponse.json({error:"Could not load user_projects."},{status:503});}}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Authentication required."},{status:401});const db=getDb();if(!db)return NextResponse.json({error:"Database unavailable."},{status:503});try{const b=await req.json();const key=typeof b.projectKey==="string"?b.projectKey:"";const title=typeof b.title==="string"?b.title.trim():"";if(!key||!title)return NextResponse.json({error:"Project is required."},{status:400});const m=(MISSIONS[typeof b.targetRole==="string"?b.targetRole:""]||[]).find(x=>x.id===key);const milestones=(m?.milestones||[]).map((x:string,i:number)=>({id:key+"-"+i,title:x,completed:false}));const r=await db.query("insert into user_projects(user_id,project_key,title,status,milestones,evidence) values($1,$2,$3,'in-progress',$4::jsonb,'[]'::jsonb) on conflict(user_id,project_key) do update set updated_at=now() returning id,project_key,title,status,milestones,evidence,created_at,updated_at",[s.userId,key,title,JSON.stringify(milestones)]);return NextResponse.json({project:r.rows[0]},{status:201});}catch{return NextResponse.json({error:"Could not start project."},{status:503});}}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:"Authentication required."},{status:401});const db=getDb();if(!db)return NextResponse.json({error:"Database unavailable."},{status:503});try{const b=await req.json();const id=typeof b.id==="string"?b.id:"";if(!id)return NextResponse.json({error:"Project id is required."},{status:400});const r=await db.query("select milestones from user_projects where id=$1 and user_id=$2",[id,s.userId]);if(!r.rowCount)return NextResponse.json({error:"Project not found."},{status:404});const milestones=Array.isArray(r.rows[0].milestones)?r.rows[0].milestones:[];const idx=milestones.findIndex((x:any)=>x.id===b.milestoneId);if(idx<0)return NextResponse.json({error:"Milestone not found."},{status:404});milestones[idx].completed=Boolean(b.completed);const complete=milestones.length>0&&milestones.every((x:any)=>x.completed);const u=await db.query("update user_projects set milestones=$1::jsonb,status=$2,evidence=case when $2='completed' then jsonb_build_array(jsonb_build_object('type','project','title',title,'createdAt',now())) else evidence end,updated_at=now() where id=$3 and user_id=$4 returning id,project_key,title,status,milestones,evidence,created_at,updated_at",[JSON.stringify(milestones),complete?"completed":"in-progress",id,s.userId]);return NextResponse.json({project:u.rows[0]});}catch{return NextResponse.json({error:"Could not update project."},{status:503});}}