"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, Circle, Clock3, Lock, Rocket, Sparkles, Target } from "lucide-react";

type Item={id:string;title:string;description:string;stage:string;item_type:string;status:"locked"|"available"|"in_progress"|"completed";completed_at?:string|null;skill_ids?:string[]};
type Goal={id:string;title:string;targetRole:string;targetLocation:string;workMode:string};
const stageOrder=["Direction","Skills","Proof","Job Ready","Applications","Interview"];

export default function CareerRoadmap(){
 const [goal,setGoal]=useState<Goal|null>(null),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[expanded,setExpanded]=useState("Skills"),[saving,setSaving]=useState("");
 useEffect(()=>{fetch("/api/career-roadmap",{cache:"no-store"}).then(async r=>{if(r.status===401){location.href="/auth";return null} const x=await r.json();if(!r.ok)throw new Error(x.error);return x}).then(x=>{if(x){setGoal(x.goal);setItems(x.items??[])}}).catch(e=>setError(e.message||"Could not load roadmap.")).finally(()=>setLoading(false))},[]);
 const done=items.filter(i=>i.status==="completed").length, progress=items.length?Math.round(done/items.length*100):0;
 const grouped=useMemo(()=>stageOrder.map(stage=>({stage,items:items.filter(i=>i.stage===stage)})).filter(x=>x.items.length),[items]);
 async function update(item:Item){const next=item.status==="completed"?"available":"completed";setSaving(item.id);try{const r=await fetch("/api/career-roadmap",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status:next})});const x=await r.json();if(!r.ok)throw new Error(x.error);setItems(v=>v.map(i=>i.id===item.id?{...i,status:x.item.status,completed_at:x.item.completed_at}:i))}catch(e){setError(e instanceof Error?e.message:"Could not update item.")}finally{setSaving("")}}
 if(loading)return <main className="min-h-screen bg-[#08090d] text-zinc-100 grid place-items-center text-sm text-zinc-500">Building your roadmap...</main>;
 return <main className="min-h-screen bg-[#08090d] text-zinc-100"><div className="mx-auto max-w-5xl px-5 py-7 sm:px-8">
  <header className="flex items-center justify-between border-b border-white/[.07] pb-6"><a href="/career-goal" className="flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/> Career Goal</a><div className="flex items-center gap-2 text-sm font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white text-black"><Target size={16}/></span>CareerPilot</div><span className="text-xs text-zinc-600">Career Roadmap</span></header>
  {error&&<div className="mt-6 rounded-xl border border-red-400/20 bg-red-400/[.05] p-4 text-sm text-red-300">{error}</div>}
  {!goal?<section className="py-20 text-center"><Rocket className="mx-auto text-violet-300"/><h1 className="mt-5 text-3xl font-semibold">Set a career goal first.</h1><p className="mt-3 text-sm text-zinc-500">Your roadmap is generated from your active Career Goal and Career DNA.</p><a href="/career-goal" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black">Set career goal <ArrowRight size={15}/></a></section>:
  <><section className="mt-10 rounded-3xl border border-white/[.08] bg-white/[.025] p-6 sm:p-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="flex items-center gap-2 text-xs text-violet-300"><Sparkles size={14}/> Personalized roadmap</p><h1 className="mt-2 text-4xl font-semibold tracking-[-.04em]">{goal.targetRole}</h1><p className="mt-2 text-sm text-zinc-500">{goal.workMode||"Flexible"} · {goal.targetLocation||"Location flexible"}</p></div><div className="text-right"><div className="text-3xl font-semibold">{progress}%</div><p className="text-[10px] uppercase tracking-wider text-zinc-600">complete</p></div></div><div className="mt-6 h-1.5 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400 transition-all" style={{width:progress+"%"}}/></div></section>
  <section className="mt-7 space-y-3">{grouped.map(({stage,items:stageItems})=>{const open=expanded===stage;const stageDone=stageItems.filter(i=>i.status==="completed").length;return <section key={stage} className="overflow-hidden rounded-3xl border border-white/[.07] bg-white/[.02]"><button onClick={()=>setExpanded(open?"":stage)} className="flex w-full items-center gap-4 p-5 text-left"><div className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.07] text-xs text-zinc-500">{stageDone===stageItems.length?<Check size={17} className="text-emerald-300"/>:stageOrder.indexOf(stage)+1}</div><div className="flex-1"><h2 className="font-semibold">{stage}</h2><p className="mt-1 text-xs text-zinc-600">{stageDone}/{stageItems.length} complete</p></div><ChevronDown size={17} className={"text-zinc-600 transition "+(open?"rotate-180":"")}/></button>{open&&<div className="border-t border-white/[.06] p-4 sm:p-5 space-y-2">{stageItems.map(item=><div key={item.id} className="rounded-2xl border border-white/[.06] bg-black/10 p-4"><div className="flex items-start gap-3"><button disabled={saving===item.id||item.status==="locked"} onClick={()=>update(item)} className={"mt-0.5 grid h-7 w-7 shrink-0 place-items-center rounded-full border "+(item.status==="completed"?"border-emerald-400/30 bg-emerald-400/10 text-emerald-300":"border-white/[.1] text-zinc-600")}>{item.status==="completed"?<Check size={13}/>:item.status==="locked"?<Lock size={11}/>:<Circle size={11}/>}</button><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className={"text-sm font-medium "+(item.status==="completed"?"text-zinc-500 line-through":"text-zinc-300")}>{item.title}</h3><span className="rounded-md border border-white/[.06] px-2 py-1 text-[9px] text-zinc-600">{item.item_type}</span></div><p className="mt-1 text-xs leading-5 text-zinc-600">{item.description}</p>{item.skill_ids?.length?<div className="mt-3 flex flex-wrap gap-1.5">{item.skill_ids.map(s=><span key={s} className="rounded-md bg-white/[.04] px-2 py-1 text-[9px] text-zinc-500">{s}</span>)}</div>:null}</div>{item.status==="in_progress"&&<span className="text-[9px] text-cyan-300">In progress</span>}</div></div>)}</div>}</section>})}</section>
  <div className="mt-7 flex justify-between text-xs text-zinc-600"><a href="/career-goal" className="hover:text-white">← Change goal</a><a href="/dashboard" className="flex items-center gap-1 hover:text-white">Command center <ArrowRight size={13}/></a></div></>}</div></main>
}