"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Clock3, FolderKanban, Layers3, Plus, Sparkles, Target, Trophy } from "lucide-react";
import { CareerState, ProjectRecord, loadCareerState, saveCareerState } from "../lib/career-state";
import { getSkillGapAnalysis, syncSkillRecords } from "../lib/career-intelligence";

type Mission={id:string;title:string;description:string;skills:string[];difficulty:"Beginner"|"Intermediate"|"Advanced";hours:string;outcome:string;milestones:string[]};

const MISSIONS:Record<string,Mission[]> = {
"Data Analyst":[
{id:"sales-dashboard",title:"E-commerce Sales Intelligence",description:"Turn transaction data into an executive dashboard explaining revenue, products, customers and performance.",skills:["SQL","Power BI","Data Visualization"],difficulty:"Intermediate",hours:"5–7h",outcome:"A portfolio-ready dashboard with business insights.",milestones:["Clean the dataset","Write SQL analysis","Build the dashboard","Write 5 business insights","Package the project"]},
{id:"retention-analysis",title:"Customer Retention Analysis",description:"Analyze customer behavior to identify retention patterns and actionable segments.",skills:["SQL","Python","Statistics"],difficulty:"Intermediate",hours:"5–7h",outcome:"A reproducible analysis with findings and recommendations.",milestones:["Prepare data","Define retention metrics","Analyze cohorts","Visualize findings","Write recommendations"]}],
"Business Analyst":[
{id:"ops-dashboard",title:"Operations Performance Dashboard",description:"Translate operational data into KPIs, bottlenecks and an executive reporting dashboard.",skills:["Excel","Power BI","Business Analysis"],difficulty:"Intermediate",hours:"4–6h",outcome:"Executive KPI dashboard plus recommendations.",milestones:["Define questions","Clean data","Build KPI model","Create dashboard","Present recommendations"]},
{id:"requirements-case",title:"Product Requirements Case Study",description:"Take a business problem from discovery through requirements, acceptance criteria and success metrics.",skills:["Business Analysis","Communication","Excel"],difficulty:"Beginner",hours:"3–4h",outcome:"A polished BA portfolio case study.",milestones:["Frame problem","Identify stakeholders","Write requirements","Define acceptance criteria","Define success metrics"]}],
"Product Analyst":[{id:"product-funnel",title:"Product Funnel & Conversion Analysis",description:"Analyze a product funnel, identify drop-offs and propose measurable experiments.",skills:["SQL","Product Analytics","Data Visualization"],difficulty:"Intermediate",hours:"5–7h",outcome:"A product analytics case study.",milestones:["Map funnel","Calculate conversion","Find drop-offs","Visualize journey","Propose experiments"]}],
"Data Scientist":[{id:"churn-model",title:"Customer Churn Prediction",description:"Build an end-to-end supervised learning project from exploration to model evaluation.",skills:["Python","Statistics","Machine Learning"],difficulty:"Advanced",hours:"8–12h",outcome:"A reproducible ML project with evaluation and README.",milestones:["Explore dataset","Engineer features","Train baseline","Evaluate models","Explain business impact"]}]
};
const FALLBACK:Mission[]=[{id:"real-world-case",title:"Real-world Data Case Study",description:"Take a public dataset, answer a real business question and turn the findings into a portfolio project.",skills:["Data Analysis","Communication"],difficulty:"Beginner",hours:"3–5h",outcome:"A concise case study with findings and recommendations.",milestones:["Choose question","Prepare data","Analyze problem","Create visuals","Write case study"]}];

export default function ProjectsPage(){
const [state,setState]=useState<CareerState|null>(null); const [selected,setSelected]=useState<Mission|null>(null);
useEffect(()=>{const r=()=>setState(loadCareerState());r();window.addEventListener("careerpilot-state-updated",r);return()=>window.removeEventListener("careerpilot-state-updated",r)},[]);
const missions=useMemo(()=>{if(!state?.targetRole)return[];const gaps=getSkillGapAnalysis(syncSkillRecords(state));const req=new Set(gaps.map(x=>x.skill.toLowerCase()));return (MISSIONS[state.targetRole]??FALLBACK).slice().sort((a,b)=>b.skills.filter(s=>req.has(s.toLowerCase())).length-a.skills.filter(s=>req.has(s.toLowerCase())).length)},[state]);
if(!state)return <Loading/>;
const currentState=state;
const completed=state.projects.filter(p=>p.status==="completed").length, active=state.projects.filter(p=>p.status==="in-progress").length;
function start(m:Mission){if(currentState.projects.some(p=>p.id===m.id)){setSelected(m);return}const p:ProjectRecord={id:m.id,title:m.title,description:m.description,skills:m.skills,difficulty:m.difficulty,status:"in-progress",milestones:m.milestones.map((title,i)=>({id:m.id+"-"+i,title,completed:false})),createdAt:new Date().toISOString()};const n={...currentState,projects:[...currentState.projects,p],lastActionId:"project-"+m.id};saveCareerState(n);setState(n);setSelected(m)}
function toggle(id:string,mid:string){const old=currentState.projects.find(p=>p.id===id)!;const ps=currentState.projects.map(p=>p.id!==id?p:{...p,milestones:p.milestones.map(m=>m.id===mid?{...m,completed:!m.completed}:m)});const p=ps.find(x=>x.id===id)!;const done=p.milestones.every(m=>m.completed),was=old.status==="completed";const final: ProjectRecord[] = ps.map(x => x.id === id ? { ...p, status: done ? ("completed" as const) : ("in-progress" as const), completedAt: done ? new Date().toISOString() : undefined } : x);const n={...currentState,projects:final,evidence:done&&!was?[...currentState.evidence,{id:"project-"+id,type:"project" as const,title:p.title,skillNames:p.skills,strength:70,createdAt:new Date().toISOString()}]:currentState.evidence,progress:{...currentState.progress,completedProjects:completed+(done&&!was?1:0),xp:currentState.progress.xp+(done&&!was?150:10)}};saveCareerState(n);setState(n)}
return <main className="min-h-screen bg-[#08090d] text-zinc-100"><div className="relative mx-auto max-w-[1250px] px-5 py-7 sm:px-8 lg:px-10">
<header className="flex items-center justify-between border-b border-white/[.07] pb-6"><a href="/dashboard" className="flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/> Command Center</a><div className="flex items-center gap-2 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white text-black"><FolderKanban size={16}/></span>CareerPilot</div><span className="text-xs text-zinc-600">Project Intelligence</span></header>
<section className="py-9"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs text-violet-300"><Sparkles size={14}/> Proof of ability</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Build projects that make your skills <span className="text-violet-300">believable.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-500">Turn your skill gaps into practical missions. Completed projects become evidence for the rest of CareerPilot.</p></div><div className="rounded-2xl border border-white/[.07] bg-white/[.025] px-5 py-4"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Target role</p><p className="mt-2 font-medium">{state.targetRole||"Not set"}</p></div></div></section>
<section className="grid gap-4 md:grid-cols-4"><Metric icon={Target} label="Recommended" value={String(missions.length)} note="role-aligned"/><Metric icon={Layers3} label="In progress" value={String(active)} note="active builds"/><Metric icon={Trophy} label="Completed" value={String(completed)} note="portfolio projects"/><Metric icon={Sparkles} label="XP" value={String(state.progress.xp)} note="career progress"/></section>
<section className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-3">{missions.map(m=><button key={m.id} onClick={()=>setSelected(m)} className={"w-full rounded-3xl border p-5 text-left "+(selected?.id===m.id?"border-violet-300/25 bg-violet-300/[.045]":"border-white/[.07] bg-white/[.025]")}><div className="flex justify-between gap-4"><div><span className="rounded-full bg-white/[.05] px-2 py-1 text-[9px] text-zinc-500">{m.difficulty}</span><h2 className="mt-3 text-lg font-semibold">{m.title}</h2><p className="mt-2 text-xs leading-5 text-zinc-600">{m.description}</p></div><ChevronRight size={17}/></div><div className="mt-4 flex flex-wrap gap-2">{m.skills.map(s=><span key={s} className="rounded-full border border-white/[.07] px-2.5 py-1 text-[10px] text-zinc-500">{s}</span>)}</div><div className="mt-4 flex gap-4 text-[10px] text-zinc-600"><span className="flex gap-1 items-center"><Clock3 size={12}/>{m.hours}</span><span>{m.milestones.length} milestones</span></div></button>)}</div>
{selected?<aside className="rounded-3xl border border-violet-300/15 bg-violet-300/[.045] p-6"><p className="text-[10px] uppercase tracking-wider text-violet-300">Project mission</p><h2 className="mt-2 text-2xl font-semibold">{selected.title}</h2><p className="mt-3 text-sm leading-6 text-zinc-500">{selected.description}</p><div className="mt-5 rounded-2xl border border-white/[.06] p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Outcome</p><p className="mt-2 text-sm">{selected.outcome}</p></div>{(()=>{const p=state.projects.find(x=>x.id===selected.id);const ms=p?.milestones??selected.milestones.map((title,i)=>({id:selected.id+"-"+i,title,completed:false}));const done=ms.filter(m=>m.completed).length;return <><div className="mt-6 flex justify-between text-xs text-zinc-500"><span>Build progress</span><span>{done}/{ms.length}</span></div><div className="mt-2 h-1.5 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:done/ms.length*100+"%"}}/></div><div className="mt-5 space-y-2">{ms.map((m,i)=><button disabled={!p} key={m.id} onClick={()=>p&&toggle(p.id,m.id)} className={"flex w-full items-center gap-3 rounded-xl border p-3 text-left "+(m.completed?"border-emerald-400/15 bg-emerald-400/[.04]":"border-white/[.06] bg-black/10")}>{m.completed?<Check size={15} className="text-emerald-300"/>:<span className="grid h-5 w-5 place-items-center rounded-full border border-white/[.1] text-[9px]">{i+1}</span>}<span className="text-xs">{m.title}</span></button>)}</div>{!p&&<button onClick={()=>start(selected)} className="mt-6 flex w-full justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black"><Plus size={16}/> Start project</button>}{p?.status==="completed"&&<div className="mt-6 flex items-center justify-center gap-2 rounded-xl border border-emerald-400/15 bg-emerald-400/[.04] p-4 text-xs text-emerald-300"><Check size={14}/> Evidence added to Career State</div>}</>})()}</aside>:<div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-7"><FolderKanban className="text-violet-300"/><h2 className="mt-5 text-2xl font-semibold">Choose a project mission</h2><p className="mt-3 text-sm text-zinc-500">Select a mission to see milestones and start building.</p></div>}</section>
<footer className="border-t border-white/[.06] py-7 mt-8 text-[10px] text-zinc-700">CareerPilot · Discover. Build. Prove. Move.</footer></div></main>
}
function Metric({icon:Icon,label,value,note}:{icon:typeof Target;label:string;value:string;note:string}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex items-center gap-2 text-zinc-600"><Icon size={15}/><span className="text-[10px] uppercase tracking-wider">{label}</span></div><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-zinc-600">{note}</p></div>}
function Loading(){return <main className="flex min-h-screen items-center justify-center bg-[#08090d] text-zinc-500">Loading Project Intelligence...</main>}
