"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, FileText, MessageSquare, Plus, Search, Target, X } from "lucide-react";
import { ApplicationRecord, ApplicationStage, CareerState, loadCareerState, saveCareerState } from "../lib/career-state";

const STAGES: {id:ApplicationStage;label:string}[]=[
 {id:"saved",label:"Saved"},{id:"ready-to-apply",label:"Ready to Apply"},{id:"applied",label:"Applied"},{id:"screening",label:"Screening"},{id:"interview",label:"Interview"},{id:"offer",label:"Offer"},{id:"rejected",label:"Rejected"},{id:"withdrawn",label:"Withdrawn"}
];

export default function ApplicationsPage(){
 const [state,setState]=useState<CareerState|null>(null); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<ApplicationRecord|null>(null);
 useEffect(()=>{const r=()=>setState(loadCareerState());r();fetch("/api/applications").then(x=>x.json()).then(x=>{if(Array.isArray(x.applications)){const remote=x.applications;setState(s=>s?{...s,applications:remote}:s)}}).catch(()=>{});window.addEventListener("careerpilot-state-updated",r);return()=>window.removeEventListener("careerpilot-state-updated",r)},[]);
 if(!state)return <Loading/>; const current=state;
 const apps=Array.isArray(current.applications) ? current.applications.filter(a=>a && typeof a==="object" && typeof a.id==="string") : [];
 const opportunities=Array.isArray(current.opportunities) ? current.opportunities.filter(o=>o && typeof o==="object" && typeof o.id==="string") : [];
 const filtered=apps.filter(a=>!query||(`${a.title??""} ${a.company??""} ${a.location??""}`).toLowerCase().includes(query.toLowerCase()));
 function addFromOpportunity(){const saved=opportunities.filter(o=>o.saved);const existing=new Set(apps.map(a=>a.opportunityId));const fresh=saved.filter(o=>!existing.has(o.id));if(!fresh.length)return;const now=new Date().toISOString();const added=fresh.map(o=>({id:"app-"+o.id,opportunityId:o.id,title:o.title,company:o.company,location:o.location,stage:"ready-to-apply" as const,createdAt:now,updatedAt:now}));const n={...current,applications:[...apps,...added]};saveCareerState(n);setState(n);}
 async function update(id:string,patch:Partial<ApplicationRecord>){const next=apps.map(a=>a.id===id?{...a,...patch,updatedAt:new Date().toISOString()}:a);const n={...current,applications:next};saveCareerState(n);setState(n);setSelected(next.find(a=>a.id===id)??null); fetch("/api/applications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...patch})}).catch(()=>{});}
 const counts=Object.fromEntries(STAGES.map(s=>[s.id,apps.filter(a=>a.stage===s.id).length]));
 return <main className="min-h-screen bg-[#08090d] text-zinc-100"><div className="mx-auto max-w-[1400px] px-5 py-7 sm:px-8 lg:px-10">
 <header className="flex items-center justify-between border-b border-white/[.07] pb-6"><a href="/jobs" className="flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/> Job Intelligence</a><div className="flex items-center gap-2 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white text-black">C</span>CareerPilot</div><span className="text-xs text-zinc-600">Application Command Center</span></header>
 <section className="py-9"><p className="text-xs text-violet-300">Application intelligence</p><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Turn opportunities into a <span className="text-violet-300">career pipeline.</span></h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-500">Track every application, preserve the context behind it, and always know the next move.</p></section>
 <div className="grid gap-3 sm:grid-cols-4">{[["Active",apps.filter(a=>!["rejected","withdrawn"].includes(a.stage)).length],["Applied",counts.applied],["Interviews",counts.interview],["Offers",counts.offer]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><p className="text-xs text-zinc-600">{l}</p><p className="mt-3 text-3xl font-semibold">{v}</p></div>)}</div>
 <div className="mt-5 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={15} className="absolute left-4 top-3.5 text-zinc-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search applications..." className="w-full rounded-xl border border-white/[.07] bg-white/[.025] py-3 pl-11 pr-4 text-sm outline-none placeholder:text-zinc-700"/></div><button onClick={addFromOpportunity} className="flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-semibold text-black"><Plus size={14}/> Import saved opportunities</button></div>
 <section className="mt-6 overflow-x-auto pb-3"><div className="grid min-w-[1180px] grid-cols-8 gap-3">{STAGES.map(stage=><div key={stage.id} className="rounded-2xl border border-white/[.06] bg-white/[.018] p-3"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-zinc-600">{stage.label}</span><span className="text-[10px] text-zinc-700">{counts[stage.id]}</span></div><div className="space-y-2">{filtered.filter(a=>a.stage===stage.id).map(a=><button key={a.id} onClick={()=>setSelected(a)} className="w-full rounded-xl border border-white/[.06] bg-black/15 p-3 text-left hover:border-violet-300/20"><p className="text-xs font-medium">{a.title}</p><p className="mt-1 text-[10px] text-zinc-600">{a.company}</p>{a.fitSignal!==undefined&&<p className="mt-2 text-[10px] text-violet-300">{a.fitSignal} fit</p>}</button>)}</div></div>)}</div></section>
 {selected&&<Detail app={selected} onClose={()=>setSelected(null)} onUpdate={update}/>}
 <div className="mt-5 rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-center gap-2 text-sm font-semibold"><Target size={16} className="text-violet-300"/> Application context</div><p className="mt-2 max-w-2xl text-xs leading-5 text-zinc-600">CareerPilot keeps the job, fit signal, resume version, preparation notes and outcome connected so the tracker becomes intelligence, not a spreadsheet.</p></div>
 </div></main>
}

function Detail({app,onClose,onUpdate}:{app:ApplicationRecord;onClose:()=>void;onUpdate:(id:string,p:Partial<ApplicationRecord>)=>void}){
 return <div className="fixed inset-0 z-50 bg-black/70 p-4 backdrop-blur-sm"><div className="mx-auto mt-10 max-w-xl rounded-3xl border border-white/[.08] bg-[#101116] p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs text-violet-300">Application</p><h2 className="mt-2 text-2xl font-semibold">{app.title}</h2><p className="mt-1 text-sm text-zinc-500">{app.company} · {app.location}</p></div><button onClick={onClose} className="text-zinc-500"><X/></button></div>
 <div className="mt-6 grid gap-3 sm:grid-cols-2"><label className="text-xs text-zinc-500">Stage<select value={app.stage} onChange={e=>onUpdate(app.id,{stage:e.target.value as ApplicationStage})} className="mt-2 w-full rounded-xl border border-white/[.07] bg-black/20 p-3 text-xs text-zinc-300">{STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label className="text-xs text-zinc-500">Resume version<input value={app.resumeVersion??""} onChange={e=>onUpdate(app.id,{resumeVersion:e.target.value})} placeholder="e.g. Data Analyst v2" className="mt-2 w-full rounded-xl border border-white/[.07] bg-black/20 p-3 text-xs text-zinc-300 outline-none"/></label></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-zinc-500"><CalendarDays size={13} className="mb-2"/>Follow-up date<input type="date" value={app.followUpAt?.slice(0,10)??""} onChange={e=>onUpdate(app.id,{followUpAt:e.target.value})} className="w-full rounded-xl border border-white/[.07] bg-black/20 p-3 text-xs text-zinc-300"/></label><label className="text-xs text-zinc-500"><CalendarDays size={13} className="mb-2"/>Interview date<input type="date" value={app.interviewAt?.slice(0,10)??""} onChange={e=>onUpdate(app.id,{interviewAt:e.target.value})} className="w-full rounded-xl border border-white/[.07] bg-black/20 p-3 text-xs text-zinc-300"/></label></div>
 <label className="mt-4 block text-xs text-zinc-500"><MessageSquare size={13} className="mb-2"/>Notes<textarea value={app.notes??""} onChange={e=>onUpdate(app.id,{notes:e.target.value})} placeholder="Interview notes, recruiter details, preparation..." className="min-h-28 w-full resize-y rounded-xl border border-white/[.07] bg-black/20 p-3 text-xs leading-5 text-zinc-300 outline-none"/></label>
 <div className="mt-5"><a href="/resume-intelligence" className="flex items-center justify-center gap-2 rounded-xl border border-white/[.07] py-3 text-xs text-zinc-400"><FileText size={14}/> Resume Intelligence</a></div>
 </div></div>
}
function Loading(){return <main className="flex min-h-screen items-center justify-center bg-[#08090d] text-zinc-500">Loading Application Command Center...</main>}
