"use client";
import { useEffect, useMemo, useState } from "react";
import { AlertCircle, ArrowLeft, ArrowRight, Brain, CheckCircle2, FileText, Search, Sparkles, Target, TrendingUp, Upload } from "lucide-react";
import { CareerState, loadCareerState } from "../lib/career-state";
import { getSkillGapAnalysis, syncSkillRecords } from "../lib/career-intelligence";
const RESUME_KEY = "careerpilot-resume-text";

export default function ResumeIntelligencePage(){
 const [state,setState]=useState<CareerState|null>(null); const [resume,setResume]=useState(""); const [analyzed,setAnalyzed]=useState(false);
 useEffect(()=>{setState(loadCareerState());const saved=window.localStorage.getItem(RESUME_KEY)||"";setResume(saved);setAnalyzed(saved.length>0)},[]);
 if(!state)return <Loading/>; const current=state;
 const gaps=getSkillGapAnalysis(syncSkillRecords(current)); const role=current.targetRole||"your target role"; const text=resume.toLowerCase();
 const required=gaps.map(x=>x.skill); const matched=required.filter(s=>text.includes(s.toLowerCase()));
 const projects=current.evidence.filter(e=>e.type==="project"); const evidenceSkills=new Set(projects.flatMap(e=>e.skillNames.map(s=>s.toLowerCase())));
 const backed=required.filter(s=>evidenceSkills.has(s.toLowerCase())); const sections=["experience","education","skills","project","summary","objective","certification"]; const found=sections.filter(s=>text.includes(s));
 const contact=/@|\+?\d[\d\s-]{8,}/.test(resume);
 const score=analyzed&&resume.trim()?Math.min(100,Math.round(matched.length/Math.max(required.length,1)*45+backed.length/Math.max(required.length,1)*25+Math.min(found.length/5,1)*15+(contact?10:0)+(resume.length>800?5:0))):0;
 const missing=required.filter(s=>!text.includes(s.toLowerCase()));
 const suggestions=[...missing.slice(0,3).map(s=>"Add "+s+" only if you genuinely have the skill or relevant evidence."),...(projects.length===0?["Complete a CareerPilot project so your resume has practical evidence to reference."]:[]),...(resume.length>0&&resume.length<800?["Add enough detail to show impact, tools used and outcomes without padding the resume."]:[])];
 function analyze(){window.localStorage.setItem(RESUME_KEY,resume);setAnalyzed(true)}
 return <main className="min-h-screen bg-[#08090d] text-zinc-100"><div className="mx-auto max-w-[1250px] px-5 py-7 sm:px-8 lg:px-10">
 <header className="flex items-center justify-between border-b border-white/[.07] pb-6"><a href="/dashboard" className="flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/> Command Center</a><div className="flex items-center gap-2 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white text-black"><FileText size={16}/></span>CareerPilot</div><span className="text-xs text-zinc-600">Resume Intelligence</span></header>
 <section className="py-9"><div className="flex items-center gap-2 text-xs text-violet-300"><Sparkles size={14}/> Career asset intelligence</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Make your resume tell the <span className="text-violet-300">right career story.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-500">CareerPilot compares your resume with your target role, skills and portfolio evidence. It does not invent experience or achievements.</p></section>
 <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
 <div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-zinc-600">Resume input</p><h2 className="mt-2 text-xl font-semibold">Paste your current resume</h2></div><Upload className="text-violet-300" size={19}/></div><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text here..." className="mt-5 min-h-[330px] w-full resize-y rounded-2xl border border-white/[.08] bg-black/20 p-4 text-sm leading-6 text-zinc-300 outline-none placeholder:text-zinc-700"/><div className="mt-4 flex items-center justify-between gap-4"><span className="text-[10px] text-zinc-700">{resume.length.toLocaleString()} characters · saved locally</span><button onClick={analyze} disabled={!resume.trim()} className="flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black disabled:opacity-30">Analyze resume <ArrowRight size={15}/></button></div></div>
 <div className="rounded-3xl border border-violet-300/15 bg-gradient-to-b from-violet-300/[.07] to-white/[.02] p-6"><div className="flex items-center gap-2 text-sm text-zinc-400"><Target size={16}/> Target role</div><h2 className="mt-3 text-2xl font-semibold">{role}</h2><p className="mt-2 text-xs text-zinc-600">Analysis uses your existing CareerPilot state.</p><div className="mt-6 grid grid-cols-2 gap-3"><Stat label="Role skills" value={String(required.length)}/><Stat label="Matched" value={analyzed?String(matched.length):"—"}/><Stat label="Projects" value={String(projects.length)}/><Stat label="Evidence skills" value={analyzed?String(backed.length):"—"}/></div><div className="mt-6 rounded-2xl border border-white/[.07] bg-black/10 p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Resume alignment</p><div className="mt-3 flex items-end gap-2"><span className="text-5xl font-semibold">{analyzed?score:"—"}</span><span className="mb-1 text-sm text-zinc-600">/ 100</span></div>{analyzed&&<div className="mt-4 h-1.5 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:score+"%"}}/></div>}<p className="mt-3 text-xs leading-5 text-zinc-600">{analyzed?"Calculated from skills, evidence and structure.":"Paste your resume to calculate an alignment signal."}</p></div></div></section>
 {analyzed&&<><section className="mt-6 grid gap-4 md:grid-cols-3"><Diagnostic title="Skill coverage" value={Math.round(matched.length/Math.max(required.length,1)*100)} detail={matched.length+" of "+required.length+" target skills found"}/><Diagnostic title="Evidence coverage" value={Math.round(backed.length/Math.max(required.length,1)*100)} detail={backed.length+" target skills backed by projects"}/><Diagnostic title="Structure signal" value={Math.round(found.length/7*100)} detail={found.length+" common sections detected"}/></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><Panel icon={<AlertCircle size={19}/>} title="Evidence & skill gaps" text="Gaps against your current target role, not claims about what you can or cannot do.">{(missing.length?missing:["No target skills are missing from the text."]).map(s=><div key={s} className="rounded-xl border border-white/[.06] p-3 text-xs text-zinc-400">{s}{!missing.length&&<CheckCircle2 className="ml-2 inline text-emerald-300" size={13}/>}</div>)}</Panel><Panel icon={<Brain size={19}/>} title="CareerPilot recommendations" text="Generated from your actual career state.">{suggestions.length?suggestions.map((s,i)=><div key={s} className="flex gap-3 rounded-xl border border-white/[.06] p-3"><span className="text-xs text-violet-300">{i+1}</span><p className="text-xs leading-5 text-zinc-400">{s}</p></div>):<p className="text-xs text-emerald-300">No immediate recommendations.</p>}</Panel></section>
 <section className="mt-6 rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-center gap-2 text-sm text-zinc-400"><Search size={16}/> Job Description Matcher</div><h2 className="mt-2 text-xl font-semibold">Compare this resume with a real job</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-zinc-600">The next layer will compare your resume and Career DNA against a pasted job description.</p><div className="mt-5 flex gap-3 text-xs text-zinc-600"><span className="rounded-full border border-white/[.07] px-3 py-1.5">Job Intelligence</span><a href="/projects" className="text-violet-300">View project evidence →</a></div></section></>}
 {!analyzed&&<section className="mt-6 rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-center gap-3 text-sm"><TrendingUp size={17} className="text-violet-300"/> Paste your resume to run the first analysis.</div></section>}
 <footer className="mt-8 border-t border-white/[.06] py-7 text-[10px] text-zinc-700">CareerPilot · Discover. Build. Prove. Move.</footer></div></main>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[.07] bg-black/10 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-700">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
function Diagnostic({title,value,detail}:{title:string;value:number;detail:string}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex justify-between"><p className="font-medium">{title}</p><span className="text-xl font-semibold text-violet-300">{value}</span></div><div className="mt-4 h-1.5 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-violet-400" style={{width:value+"%"}}/></div><p className="mt-2 text-xs text-zinc-600">{detail}</p></div>}
function Panel({icon,title,text,children}:{icon:React.ReactNode;title:string;text:string;children:React.ReactNode}){return <div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-300/10 text-violet-300">{icon}</div><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs text-zinc-600">{text}</p></div></div><div className="mt-5 space-y-2">{children}</div></div>}
function Loading(){return <main className="flex min-h-screen items-center justify-center bg-[#08090d] text-zinc-500">Loading Resume Intelligence...</main>}