"use client";
import { useEffect, useState } from "react";
import { AlertCircle, ArrowLeft, ArrowRight, Brain, CheckCircle2, FileText, Search, Sparkles, Target, TrendingUp, Upload } from "lucide-react";
import { CareerState, loadCareerState } from "../lib/career-state";

type Analysis={atsScore:number;roleAlignment:number;keywordCoverage:number;evidenceScore:number;structureScore:number;gaps:{skill:string;type:string}[];recommendations:string[];jdCoverage:number;jdMatched:string[];jdGaps:string[]};
export default function ResumeIntelligencePage(){
 const [state,setState]=useState<CareerState|null>(null),[resume,setResume]=useState(""),[analysis,setAnalysis]=useState<Analysis|null>(null),[jobDescription,setJobDescription]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{setState(loadCareerState());fetch("/api/resume-intelligence").then(r=>r.json()).then(x=>{if(x.resume)setResume(x.resume.content)}).catch(()=>{})},[]);
 if(!state)return <Loading/>; const role=state.targetRole||"your target role";
 async function analyze(){if(!resume.trim())return;setBusy(true);setError("");try{const r=await fetch("/api/resume-intelligence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content:resume,jobDescription})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Analysis failed");setAnalysis(x.analysis)}catch(e){setError(e instanceof Error?e.message:"Analysis failed")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-[#08090d] text-zinc-100"><div className="mx-auto max-w-[1250px] px-5 py-7 sm:px-8 lg:px-10">
 <header className="flex items-center justify-between border-b border-white/[.07] pb-6"><a href="/dashboard" className="flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/> Command Center</a><div className="flex items-center gap-2 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white text-black"><FileText size={16}/></span>CareerPilot</div><span className="text-xs text-zinc-600">Resume Intelligence</span></header>
 <section className="py-9"><div className="flex items-center gap-2 text-xs text-violet-300"><Sparkles size={14}/> Career asset intelligence</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Make your resume tell the <span className="text-violet-300">right career story.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-500">CareerPilot compares your resume with your target role, verified skills and evidence. It never invents experience or achievements.</p></section>
 <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-wider text-zinc-600">Resume input</p><h2 className="mt-2 text-xl font-semibold">Paste your current resume</h2></div><Upload className="text-violet-300" size={19}/></div><textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text here..." className="mt-5 min-h-[330px] w-full resize-y rounded-2xl border border-white/[.08] bg-black/20 p-4 text-sm leading-6 text-zinc-300 outline-none placeholder:text-zinc-700"/><div className="mt-4 flex items-center justify-between gap-4"><span className="text-[10px] text-zinc-700">{resume.length.toLocaleString()} characters · persisted to your account</span><button onClick={analyze} disabled={!resume.trim()||busy} className="flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-semibold text-black disabled:opacity-30">{busy?"Analyzing...":"Analyze resume"} <ArrowRight size={15}/></button></div>{error&&<p className="mt-3 text-xs text-red-300">{error}</p>}</div>
 <div className="rounded-3xl border border-violet-300/15 bg-gradient-to-b from-violet-300/[.07] to-white/[.02] p-6"><div className="flex items-center gap-2 text-sm text-zinc-400"><Target size={16}/> Target role</div><h2 className="mt-3 text-2xl font-semibold">{role}</h2><p className="mt-2 text-xs text-zinc-600">Analysis uses your stored CareerPilot profile and skill evidence.</p>{analysis?<><div className="mt-6 grid grid-cols-2 gap-3"><Stat label="ATS signal" value={String(analysis.atsScore)}/><Stat label="Role alignment" value={String(analysis.roleAlignment)+"%"}/><Stat label="Keyword coverage" value={String(analysis.keywordCoverage)+"%"}/><Stat label="Evidence coverage" value={String(analysis.evidenceScore)+"%"}/></div><div className="mt-6 rounded-2xl border border-white/[.07] bg-black/10 p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Resume alignment</p><div className="mt-3 flex items-end gap-2"><span className="text-5xl font-semibold">{analysis.atsScore}</span><span className="mb-1 text-sm text-zinc-600">/ 100</span></div><div className="mt-4 h-1.5 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{width:analysis.atsScore+"%"}}/></div></div></>:<div className="mt-6 rounded-2xl border border-white/[.07] bg-black/10 p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Resume alignment</p><p className="mt-3 text-3xl font-semibold">—</p><p className="mt-2 text-xs text-zinc-600">Run an analysis to calculate role alignment.</p></div>}</div></section>
 {analysis&&<><section className="mt-6 grid gap-4 md:grid-cols-3"><Diagnostic title="Skill coverage" value={analysis.keywordCoverage} detail="Target skills found in the resume"/><Diagnostic title="Evidence coverage" value={analysis.evidenceScore} detail="Target skills supported by stored evidence"/><Diagnostic title="Structure signal" value={analysis.structureScore} detail="Standard resume sections detected"/></section>
 <section className="mt-6 grid gap-6 lg:grid-cols-2"><Panel icon={<AlertCircle size={19}/>} title="Evidence & skill gaps" text="Gaps against your current target role.">{(analysis.gaps.length?analysis.gaps.map(x=>x.skill):["No target skill gaps detected."]).map(s=><div key={s} className="rounded-xl border border-white/[.06] p-3 text-xs text-zinc-400">{s}{!analysis.gaps.length&&<CheckCircle2 className="ml-2 inline text-emerald-300" size={13}/>}</div>)}</Panel><Panel icon={<Brain size={19}/>} title="CareerPilot recommendations" text="Based on your stored profile and resume evidence.">{analysis.recommendations.map((s,i)=><div key={s} className="flex gap-3 rounded-xl border border-white/[.06] p-3"><span className="text-xs text-violet-300">{i+1}</span><p className="text-xs leading-5 text-zinc-400">{s}</p></div>)}</Panel></section>
 <section className="mt-6 rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-center gap-2 text-sm text-zinc-400"><Search size={16}/> Job Description Matcher</div><h2 className="mt-2 text-xl font-semibold">Compare this resume with a real job</h2><p className="mt-2 max-w-2xl text-xs leading-5 text-zinc-600">Paste a job description and CareerPilot will identify language already covered by your resume and terms you may need to address.</p><textarea value={jobDescription} onChange={e=>setJobDescription(e.target.value)} placeholder="Paste the job description here..." className="mt-5 min-h-[180px] w-full resize-y rounded-2xl border border-white/[.08] bg-black/20 p-4 text-sm leading-6 text-zinc-300 outline-none placeholder:text-zinc-700"/><div className="mt-4 flex items-center gap-4"><button onClick={analyze} disabled={!resume.trim()||!jobDescription.trim()||busy} className="rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black disabled:opacity-30">Analyze against JD</button>{analysis&&jobDescription&&<span className="text-xs text-zinc-500">JD coverage: <b className="text-violet-300">{analysis.jdCoverage}%</b></span>}</div>{analysis&&jobDescription&&<div className="mt-5 grid gap-4 md:grid-cols-2"><div><p className="mb-2 text-[10px] uppercase tracking-wider text-zinc-600">Covered terms</p><div className="flex flex-wrap gap-2">{analysis.jdMatched.map(x=><span key={x} className="rounded-full border border-emerald-300/10 bg-emerald-300/5 px-2.5 py-1 text-[11px] text-emerald-200">{x}</span>)}</div></div><div><p className="mb-2 text-[10px] uppercase tracking-wider text-zinc-600">Terms to review</p><div className="flex flex-wrap gap-2">{analysis.jdGaps.map(x=><span key={x} className="rounded-full border border-amber-300/10 bg-amber-300/5 px-2.5 py-1 text-[11px] text-amber-200">{x}</span>)}</div></div></div>}<div className="mt-5 flex gap-3 text-xs text-zinc-600"><span className="rounded-full border border-white/[.07] px-3 py-1.5">Job Intelligence</span><a href="/projects" className="text-violet-300">View project evidence →</a></div></section></>}
 {!analysis&&<section className="mt-6 rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-center gap-3 text-sm"><TrendingUp size={17} className="text-violet-300"/> Paste your resume to run the first analysis.</div></section>}
 <footer className="mt-8 border-t border-white/[.06] py-7 text-[10px] text-zinc-700">CareerPilot · Discover. Build. Prove. Move.</footer></div></main>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[.07] bg-black/10 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-700">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
function Diagnostic({title,value,detail}:{title:string;value:number;detail:string}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex justify-between"><p className="font-medium">{title}</p><span className="text-xl font-semibold text-violet-300">{value}</span></div><div className="mt-4 h-1.5 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-violet-400" style={{width:value+"%"}}/></div><p className="mt-2 text-xs text-zinc-600">{detail}</p></div>}
function Panel({icon,title,text,children}:{icon:React.ReactNode;title:string;text:string;children:React.ReactNode}){return <div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-6"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-violet-300/10 text-violet-300">{icon}</div><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-xs text-zinc-600">{text}</p></div></div><div className="mt-5 space-y-2">{children}</div></div>}
function Loading(){return <main className="flex min-h-screen items-center justify-center bg-[#08090d] text-zinc-500">Loading Resume Intelligence...</main>}