"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Bookmark, Check, ChevronRight, Clock3, ExternalLink, Filter, Globe2, MapPin, Search, Sparkles, X } from "lucide-react";
import { CareerState, OpportunityRecord, loadCareerState, saveCareerState } from "../lib/career-state";
import { getSkillGapAnalysis, syncSkillRecords } from "../lib/career-intelligence";

type Job=OpportunityRecord & { companyType:string; requirements:string[] };

const JOBS:Job[]=[
{id:"da-001",title:"Data Analyst",company:"Northstar Analytics",companyType:"Analytics",location:"Bengaluru, India",workMode:"hybrid",employmentType:"full-time",scope:"india",skills:["SQL","Excel","Power BI","Data Visualization"],experience:"0–2 years",salary:"₹6–10 LPA",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Excel","Power BI","Data Visualization"]},
{id:"da-002",title:"Junior Data Analyst",company:"Atlas Commerce",companyType:"E-commerce",location:"Remote · India",workMode:"remote",employmentType:"full-time",scope:"india",skills:["SQL","Excel","Python","Statistics"],experience:"0–2 years",salary:"₹5–8 LPA",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Excel","Python","Statistics"]},
{id:"da-003",title:"Data Analyst",company:"Orbit Systems",companyType:"Technology",location:"Remote · Worldwide",workMode:"remote",employmentType:"full-time",scope:"remote-worldwide",skills:["SQL","Python","Data Visualization","Statistics"],experience:"1–3 years",salary:"$45k–65k",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Python","Data Visualization","Statistics"]},
{id:"ba-001",title:"Business Analyst",company:"Vertex Operations",companyType:"Operations",location:"Noida, India",workMode:"onsite",employmentType:"full-time",scope:"india",skills:["Excel","Business Analysis","Communication","Power BI"],experience:"0–2 years",salary:"₹5–9 LPA",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["Excel","Business Analysis","Communication","Power BI"]},
{id:"pa-001",title:"Product Analyst",company:"Pulse Labs",companyType:"Product",location:"Remote · Worldwide",workMode:"remote",employmentType:"full-time",scope:"remote-worldwide",skills:["SQL","Product Analytics","Data Visualization"],experience:"1–3 years",salary:"$50k–75k",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Product Analytics","Data Visualization"]}
];

export default function JobsPage(){
const [state,setState]=useState<CareerState|null>(null); const [query,setQuery]=useState(""); const [mode,setMode]=useState("all"); const [scope,setScope]=useState("all"); const [selected,setSelected]=useState<Job|null>(null);
useEffect(()=>{const r=()=>setState(loadCareerState());r();window.addEventListener("careerpilot-state-updated",r);return()=>window.removeEventListener("careerpilot-state-updated",r)},[]);
const current=state;
const gaps=current ? getSkillGapAnalysis(syncSkillRecords(current)) : [];
const filtered=useMemo(()=>JOBS.filter(j=>(!query||[j.title,j.company,j.location,...j.skills].join(" ").toLowerCase().includes(query.toLowerCase()))&&(mode==="all"||j.workMode===mode)&&(scope==="all"||j.scope===scope)),[query,mode,scope]);
if(!current)return <Loading/>;
function match(j:Job){const target=new Set(gaps.map(g=>g.skill.toLowerCase()));const matched=j.skills.filter(s=>target.has(s.toLowerCase())).length;const evidence=new Set(current.evidence.flatMap(e=>e.skillNames.map(s=>s.toLowerCase())));const backed=j.skills.filter(s=>evidence.has(s.toLowerCase())).length;return Math.round((matched/j.skills.length)*70+(backed/j.skills.length)*30)}
function save(j:Job){const exists=current.opportunities.find(x=>x.id===j.id);const opportunities=exists?current.opportunities.map(x=>x.id===j.id?{...x,saved:!x.saved}:x):[...current.opportunities,{...j,saved:true}];const n={...current,opportunities};saveCareerState(n);setState(n)}
return <main className="min-h-screen bg-[#08090d] text-zinc-100"><div className="mx-auto max-w-[1280px] px-5 py-7 sm:px-8 lg:px-10">
<header className="flex items-center justify-between border-b border-white/[.07] pb-6"><a href="/dashboard" className="flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/> Command Center</a><div className="flex items-center gap-2 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white text-black">C</span>CareerPilot</div><span className="text-xs text-zinc-600">Job Intelligence</span></header>
<section className="py-9"><div className="flex items-center gap-2 text-xs text-violet-300"><Sparkles size={14}/> Opportunity intelligence</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Find opportunities that fit your <span className="text-violet-300">career state.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-500">Explore structured opportunities and see why each one fits your skills, evidence, work mode and target direction.</p></section>
<section className="rounded-3xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-4 top-3.5 text-zinc-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={"Search "+(current.targetRole||"roles, skills, companies")+"..."} className="w-full rounded-xl border border-white/[.07] bg-black/20 py-3 pl-11 pr-4 text-sm outline-none placeholder:text-zinc-700"/></div><Select value={mode} setValue={setMode} options={[["all","Any work mode"],["remote","Remote"],["hybrid","Hybrid"],["onsite","On-site"]]}/><Select value={scope} setValue={setScope} options={[["all","Any geography"],["india","India"],["international","International"],["remote-worldwide","Remote worldwide"]]}/></div></section>
<section className="mt-5 flex items-center justify-between text-xs text-zinc-600"><span>{filtered.length} structured opportunities</span><span className="flex items-center gap-1"><Filter size={13}/> Ranked against your Career State</span></section>
<section className="mt-3 grid gap-3 lg:grid-cols-[1fr_390px]"><div className="space-y-3">{filtered.map(j=><JobCard key={j.id} job={j} score={match(j)} active={selected?.id===j.id} saved={current.opportunities.some(o=>o.id===j.id&&o.saved)} onSave={()=>save(j)} onClick={()=>setSelected(j)}/>)}</div>{selected?<Detail job={selected} score={match(selected)} saved={current.opportunities.some(o=>o.id===selected.id&&o.saved)} onSave={()=>save(selected)}/>:<div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-7"><Sparkles className="text-violet-300"/><h2 className="mt-5 text-xl font-semibold">Select an opportunity</h2><p className="mt-2 text-sm leading-6 text-zinc-600">CareerPilot will explain the fit instead of giving you a mysterious match number.</p></div>}</section>
<footer className="mt-8 border-t border-white/[.06] py-7 text-[10px] text-zinc-700">CareerPilot · Opportunity intelligence · Demo opportunities are clearly labelled and ready for real-source ingestion.</footer>
</div></main>
}

function JobCard({job,score,active,saved,onSave,onClick}:{job:Job;score:number;active:boolean;saved:boolean;onSave:()=>void;onClick:()=>void}){return <div className={"rounded-3xl border p-5 "+(active?"border-violet-300/25 bg-violet-300/[.04]":"border-white/[.07] bg-white/[.025]")}><div className="flex justify-between gap-4"><button onClick={onClick} className="min-w-0 flex-1 text-left"><p className="text-xs text-zinc-600">{job.company} · {job.companyType}</p><h2 className="mt-1 text-lg font-semibold">{job.title}</h2><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-zinc-600"><span className="flex items-center gap-1"><MapPin size={12}/>{job.location}</span><span>{job.employmentType}</span><span>{job.experience}</span></div></button><div className="text-right"><p className="text-2xl font-semibold text-violet-300">{score}</p><p className="text-[9px] uppercase tracking-wider text-zinc-700">fit signal</p></div></div><div className="mt-4 flex flex-wrap gap-2">{job.skills.map(s=><span key={s} className="rounded-full border border-white/[.07] px-2.5 py-1 text-[10px] text-zinc-500">{s}</span>)}</div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-zinc-600">{job.salary||"Salary not listed"}</span><button onClick={onSave} className="rounded-xl border border-white/[.07] p-2 text-zinc-500 hover:text-white">{saved?<Bookmark size={15} fill="currentColor"/>:<Bookmark size={15}/>}</button></div></div>}

function Detail({job,score,saved,onSave}:{job:Job;score:number;saved:boolean;onSave:()=>void}){return <aside className="sticky top-6 h-fit rounded-3xl border border-violet-300/15 bg-violet-300/[.035] p-6"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-wider text-violet-300">Opportunity analysis</p><h2 className="mt-2 text-2xl font-semibold">{job.title}</h2><p className="mt-1 text-sm text-zinc-500">{job.company}</p></div><button onClick={onSave} className="text-zinc-500">{saved?<Bookmark fill="currentColor" size={18}/>:<Bookmark size={18}/>}</button></div><div className="mt-6 grid grid-cols-2 gap-3"><Box label="Fit signal" value={score+" / 100"}/><Box label="Work mode" value={job.workMode}/><Box label="Location" value={job.location}/><Box label="Experience" value={job.experience}/></div><div className="mt-6"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Requirement coverage</p><div className="mt-3 space-y-2">{job.requirements.map(r=><div key={r} className="flex items-center gap-2 rounded-xl border border-white/[.06] p-3 text-xs"><Check size={14} className="text-emerald-300"/>{r}</div>)}</div></div><div className="mt-6 rounded-2xl border border-white/[.06] p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Source</p><p className="mt-2 text-xs text-zinc-400">{job.source}</p><p className="mt-2 text-[10px] text-zinc-700">Demo data only. Real-source ingestion will replace this dataset.</p></div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black">View opportunity <ExternalLink size={14}/></button></aside>}

function Box({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[.06] bg-black/10 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-700">{label}</p><p className="mt-2 text-xs font-medium text-zinc-300">{value}</p></div>}
function Select({value,setValue,options}:{value:string;setValue:(v:string)=>void;options:string[][]}){return <select value={value} onChange={e=>setValue(e.target.value)} className="rounded-xl border border-white/[.07] bg-black/20 px-4 py-3 text-xs text-zinc-400 outline-none">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function Loading(){return <main className="flex min-h-screen items-center justify-center bg-[#08090d] text-zinc-500">Loading Job Intelligence...</main>}
