"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Bookmark, Check, ClipboardPaste, ExternalLink, Filter, MapPin, Search, Sparkles, X } from "lucide-react";
import { CareerState, OpportunityRecord, loadCareerState, saveCareerState } from "../lib/career-state";
import { getSkillGapAnalysis, syncSkillRecords } from "../lib/career-intelligence";

type Job = OpportunityRecord & { companyType: string; requirements: string[] };
type Analysis = {
  title: string; company: string; location: string; workMode: "remote"|"hybrid"|"onsite";
  employmentType: "full-time"|"part-time"|"contract"|"internship";
  scope: "india"|"international"|"remote-worldwide"; experience: string; salary?: string;
  sponsorship: "yes"|"no"|"unknown"; requiredSkills: string[]; preferredSkills: string[];
  responsibilities: string[]; education: string; raw: string;
};

const JOBS: Job[] = [
{id:"da-001",title:"Data Analyst",company:"Northstar Analytics",companyType:"Analytics",location:"Bengaluru, India",workMode:"hybrid",employmentType:"full-time",scope:"india",skills:["SQL","Excel","Power BI","Data Visualization"],experience:"0–2 years",salary:"₹6–10 LPA",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Excel","Power BI","Data Visualization"]},
{id:"da-002",title:"Junior Data Analyst",company:"Atlas Commerce",companyType:"E-commerce",location:"Remote · India",workMode:"remote",employmentType:"full-time",scope:"india",skills:["SQL","Excel","Python","Statistics"],experience:"0–2 years",salary:"₹5–8 LPA",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Excel","Python","Statistics"]},
{id:"da-003",title:"Data Analyst",company:"Orbit Systems",companyType:"Technology",location:"Remote · Worldwide",workMode:"remote",employmentType:"full-time",scope:"remote-worldwide",skills:["SQL","Python","Data Visualization","Statistics"],experience:"1–3 years",salary:"$45k–65k",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Python","Data Visualization","Statistics"]},
{id:"ba-001",title:"Business Analyst",company:"Vertex Operations",companyType:"Operations",location:"Noida, India",workMode:"onsite",employmentType:"full-time",scope:"india",skills:["Excel","Business Analysis","Communication","Power BI"],experience:"0–2 years",salary:"₹5–9 LPA",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["Excel","Business Analysis","Communication","Power BI"]},
{id:"pa-001",title:"Product Analyst",company:"Pulse Labs",companyType:"Product",location:"Remote · Worldwide",workMode:"remote",employmentType:"full-time",scope:"remote-worldwide",skills:["SQL","Product Analytics","Data Visualization"],experience:"1–3 years",salary:"$50k–75k",sponsorship:"unknown",source:"CareerPilot Demo Dataset",url:"#",saved:false,requirements:["SQL","Product Analytics","Data Visualization"]}
];

const SKILL_CATALOG=["SQL","Excel","Power BI","Python","Statistics","Data Visualization","Business Analysis","Communication","Product Analytics","Machine Learning","Problem Solving","Domain Knowledge","Tableau","R","Java","JavaScript","React","AWS","Azure","Git","Figma","Project Management"];
const normalize=(s:string)=>s.toLowerCase().replace(/[^a-z0-9+#.]/g," ").replace(/\s+/g," ").trim();
function contains(text:string, phrase:string){return normalize(text).includes(normalize(phrase));}
function extractLine(text:string, labels:string[]){const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);return lines.find(l=>labels.some(label=>normalize(l).startsWith(normalize(label))))?.replace(/^[^:]+:\s*/,"")||"";}
function parseJD(raw:string):Analysis{
 const title=extractLine(raw,["job title","position","role"])||"Untitled opportunity";
 const company=extractLine(raw,["company","organization","employer"])||"Company not specified";
 const location=extractLine(raw,["location","work location"])||"Location not specified";
 const workMode=contains(raw,"remote")?"remote":contains(raw,"hybrid")?"hybrid":"onsite";
 const employmentType=contains(raw,"internship")?"internship":contains(raw,"part-time")?"part-time":contains(raw,"contract")?"contract":"full-time";
 const scope=contains(raw,"worldwide")||contains(raw,"work from anywhere")?"remote-worldwide":contains(raw,"international")||contains(raw,"relocation")?"international":"india";
 const experience=(raw.match(/(?:\d+\s*(?:-|–|to)\s*\d+|\d+)\s*(?:years?|yrs?)/i)?.[0]||"Not specified");
 const salary=raw.match(/(?:₹|INR|\$)\s*[\d,.]+(?:\s*[-–]\s*(?:₹|INR|\$)?\s*[\d,.]+)?\s*(?:LPA|K|k)?/i)?.[0];
 const sponsorship=contains(raw,"visa sponsorship")||contains(raw,"sponsorship available")?"yes":contains(raw,"no sponsorship")||contains(raw,"without sponsorship")?"no":"unknown";
 const requiredSkills=SKILL_CATALOG.filter(s=>contains(raw,s));
 const preferredSection=raw.match(/(?:preferred|nice to have|good to have|bonus)[\s\S]{0,900}/i)?.[0]||"";
 const preferredSkills=SKILL_CATALOG.filter(s=>contains(preferredSection,s));
 const responsibilities=raw.split(/\n+/).map(x=>x.trim()).filter(x=>/^(?:[-•*]|responsibilit|you will|what you.ll do|role)/i.test(x)).slice(0,6);
 const education=extractLine(raw,["education","qualification","degree"])||"Not specified";
 return {title,company,location,workMode,employmentType,scope,experience,salary,sponsorship,requiredSkills,preferredSkills,responsibilities,education,raw};
}

export default function JobsPage(){
 const [state,setState]=useState<CareerState|null>(null); const [dbJobs,setDbJobs]=useState<Job[]>([]); const [dbMatches,setDbMatches]=useState<Record<string,any>>({});
 const [tab,setTab]=useState<"explore"|"analyze">("explore");
 const [query,setQuery]=useState(""); const [mode,setMode]=useState("all"); const [scope,setScope]=useState("all"); const [selected,setSelected]=useState<Job|null>(null);
 const [jd,setJd]=useState(""); const [analysis,setAnalysis]=useState<Analysis|null>(null); const [savedAnalysis,setSavedAnalysis]=useState(false);
 useEffect(()=>{const r=()=>setState(loadCareerState());r();window.addEventListener("careerpilot-state-updated",r); fetch("/api/jobs").then(x=>x.json()).then(x=>{if(Array.isArray(x.jobs))setDbJobs(x.jobs.map((j:any)=>({id:j.id,title:j.title,company:j.company,companyType:j.source||"Opportunity",location:j.location||"Not specified",workMode:j.work_mode||"onsite",employmentType:j.employment_type||"full-time",scope:(j.location||"").toLowerCase().includes("worldwide")?"remote-worldwide":"india",skills:Array.isArray(j.skills)?j.skills:[],experience:j.experience_requirement||"Not specified",salary:j.salary_min?`${j.salary_currency||""}${j.salary_min}${j.salary_max?`–${j.salary_max}`:""}`:"Salary not listed",sponsorship:j.visa_sponsorship===true?"yes":j.visa_sponsorship===false?"no":"unknown",source:j.source||"CareerPilot",url:j.url||"#",saved:!!j.saved,requirements:Array.isArray(j.requirements)?j.requirements:[]}))) }).catch(()=>{});fetch("/api/job-matches").then(x=>x.json()).then(x=>{if(Array.isArray(x.matches))setDbMatches(Object.fromEntries(x.matches.map((m:any)=>[m.id,m])))}).catch(()=>{});return()=>window.removeEventListener("careerpilot-state-updated",r)},[]);
 const current=state; const gaps=current?getSkillGapAnalysis(syncSkillRecords(current)):[];
 const allJobs=[...dbJobs,...JOBS.filter(j=>!dbJobs.some(d=>d.id===j.id))]; const filtered=useMemo(()=>allJobs.filter(j=>(!query||[j.title,j.company,j.location,...j.skills].join(" ").toLowerCase().includes(query.toLowerCase()))&&(mode==="all"||j.workMode===mode)&&(scope==="all"||j.scope===scope)),[query,mode,scope]);
 if(!current)return <Loading/>; const currentState=current;
 const owned=new Set([...currentState.skills,...currentState.skillRecords.filter(s=>s.currentLevel>0).map(s=>s.name)].map(normalize));
 const evidence=new Set(currentState.evidence.flatMap(e=>e.skillNames.map(normalize)));
 function scoreSkills(skills:string[]){const matched=skills.filter(s=>owned.has(normalize(s)));const backed=skills.filter(s=>evidence.has(normalize(s)));return {matched,backed,score:skills.length?Math.round((matched.length/skills.length)*70+(backed.length/skills.length)*30):0};}
 function match(j:Job){return dbMatches[j.id]?.match_score??scoreSkills(j.skills).score;}
 function breakdown(j:Job){return dbMatches[j.id]?.breakdown??{skills:scoreSkills(j.skills).score,experience:50,education:50,location:50,work_mode:50,authorization:50,seniority:50};}
 function save(j:Job){const exists=currentState.opportunities.find(x=>x.id===j.id);const opportunities=exists?currentState.opportunities.map(x=>x.id===j.id?{...x,saved:!x.saved}:x):[...currentState.opportunities,{...j,saved:true}];const n={...currentState,opportunities};saveCareerState(n);setState(n);}
 function analyze(){if(!jd.trim())return;setAnalysis(parseJD(jd));setSavedAnalysis(false);}
 function analysisScore(a:Analysis){return scoreSkills(a.requiredSkills).score;}
 function saveParsed(){if(!analysis)return;const id="jd-"+Date.now();const record:OpportunityRecord={id,title:analysis.title,company:analysis.company,location:analysis.location,workMode:analysis.workMode,employmentType:analysis.employmentType,scope:analysis.scope,skills:analysis.requiredSkills,experience:analysis.experience,salary:analysis.salary,sponsorship:analysis.sponsorship,source:"User-provided job description",url:"#",saved:true};const n={...currentState,opportunities:[...currentState.opportunities,record]};saveCareerState(n);setState(n);setSavedAnalysis(true);}
 return <main className="min-h-screen bg-[#08090d] text-zinc-100"><div className="mx-auto max-w-[1280px] px-5 py-7 sm:px-8 lg:px-10">
 <header className="flex items-center justify-between border-b border-white/[.07] pb-6"><a href="/dashboard" className="flex items-center gap-2 text-sm text-zinc-500 hover:text-white"><ArrowLeft size={16}/> Command Center</a><div className="flex items-center gap-2 font-semibold"><span className="grid h-8 w-8 place-items-center rounded-xl bg-white text-black">C</span>CareerPilot</div><span className="text-xs text-zinc-600">Job Intelligence</span></header>
 <section className="py-9"><div className="flex items-center gap-2 text-xs text-violet-300"><Sparkles size={14}/> Opportunity intelligence</div><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">{tab==="explore"?"Find opportunities that fit your":"Understand any job before you apply."} <span className="text-violet-300">{tab==="explore"?"career state.":"CareerPilot will break it down."}</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-500">{tab==="explore"?"Explore structured opportunities and see why each one fits your skills, evidence, work mode and target direction.":"Paste a real job description and CareerPilot will extract its requirements, compare them with your career state, and show exactly what is strong or missing."}</p></section>
 <div className="mb-5 flex gap-2 rounded-2xl border border-white/[.07] bg-white/[.025] p-1"><button onClick={()=>setTab("explore")} className={"rounded-xl px-4 py-2.5 text-xs "+(tab==="explore"?"bg-white text-black font-semibold":"text-zinc-500")}>Opportunity Explorer</button><button onClick={()=>setTab("analyze")} className={"rounded-xl px-4 py-2.5 text-xs "+(tab==="analyze"?"bg-white text-black font-semibold":"text-zinc-500")}>Analyze a Job Description</button></div>
 {tab==="explore"?<Explore filtered={filtered} query={query} setQuery={setQuery} mode={mode} setMode={setMode} scope={scope} setScope={setScope} selected={selected} setSelected={setSelected} current={currentState} match={match} save={save}/>:<Analyzer jd={jd} setJd={setJd} analysis={analysis} analyze={analyze} score={analysis?analysisScore(analysis):0} owned={owned} evidence={evidence} gaps={gaps} saved={savedAnalysis} save={saveParsed}/>}
 <footer className="mt-8 border-t border-white/[.06] py-7 text-[10px] text-zinc-700">CareerPilot · Job Intelligence · User-provided job descriptions stay in your current CareerPilot state.</footer>
 </div></main>
}

function Explore({filtered,query,setQuery,mode,setMode,scope,setScope,selected,setSelected,current,match,save}:{filtered:Job[];query:string;setQuery:(v:string)=>void;mode:string;setMode:(v:string)=>void;scope:string;setScope:(v:string)=>void;selected:Job|null;setSelected:(v:Job|null)=>void;current:CareerState;match:(j:Job)=>number;save:(j:Job)=>void}){
 return <><section className="rounded-3xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-4 top-3.5 text-zinc-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={"Search "+(current.targetRole||"roles, skills, companies")+"..."} className="w-full rounded-xl border border-white/[.07] bg-black/20 py-3 pl-11 pr-4 text-sm outline-none placeholder:text-zinc-700"/></div><Select value={mode} setValue={setMode} options={[["all","Any work mode"],["remote","Remote"],["hybrid","Hybrid"],["onsite","On-site"]]}/><Select value={scope} setValue={setScope} options={[["all","Any geography"],["india","India"],["international","International"],["remote-worldwide","Remote worldwide"]]}/></div></section><section className="mt-5 flex items-center justify-between text-xs text-zinc-600"><span>{filtered.length} structured opportunities</span><span className="flex items-center gap-1"><Filter size={13}/> Ranked against your skills + evidence</span></section><section className="mt-3 grid gap-3 lg:grid-cols-[1fr_390px]"><div className="space-y-3">{filtered.map(j=><JobCard key={j.id} job={j} score={match(j)} active={selected?.id===j.id} saved={current.opportunities.some(o=>o.id===j.id&&o.saved)} onSave={()=>save(j)} onClick={()=>setSelected(j)}/>)}</div>{selected?<Detail job={selected} score={match(selected)} breakdown={breakdown(selected)} saved={current.opportunities.some(o=>o.id===selected.id&&o.saved)} onSave={()=>save(selected)}/>:<div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-7"><Sparkles className="text-violet-300"/><h2 className="mt-5 text-xl font-semibold">Select an opportunity</h2><p className="mt-2 text-sm leading-6 text-zinc-600">CareerPilot will explain the fit instead of giving you a mysterious match number.</p></div>}</section></>
}

function Analyzer({jd,setJd,analysis,analyze,score,owned,evidence,gaps,saved,save}:{jd:string;setJd:(v:string)=>void;analysis:Analysis|null;analyze:()=>void;score:number;owned:Set<string>;evidence:Set<string>;gaps:{skill:string;gap:number;importance:string}[];saved:boolean;save:()=>void}){
 const matched=analysis?analysis.requiredSkills.filter(s=>owned.has(normalize(s))):[]; const backed=analysis?analysis.requiredSkills.filter(s=>evidence.has(normalize(s))):[]; const missing=analysis?analysis.requiredSkills.filter(s=>!owned.has(normalize(s))):[];
 return <section className="grid gap-4 lg:grid-cols-[1fr_430px]"><div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex items-center gap-2 text-sm font-semibold"><ClipboardPaste size={17} className="text-violet-300"/> Paste the job description</div><p className="mt-2 text-xs leading-5 text-zinc-600">Use a real JD from a company site, LinkedIn or another source. CareerPilot analyzes the text locally in this prototype.</p><textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder={"Example:\nJob Title: Data Analyst\nCompany: Example Co\nLocation: Noida, India\n\nRequirements:\n• SQL\n• Excel\n• Power BI\n• 1–2 years experience"} className="mt-5 min-h-[430px] w-full resize-y rounded-2xl border border-white/[.07] bg-black/20 p-4 text-sm leading-6 text-zinc-300 outline-none placeholder:text-zinc-700"/><button onClick={analyze} disabled={!jd.trim()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black disabled:cursor-not-allowed disabled:opacity-30"><Sparkles size={15}/> Analyze job</button></div>
 <div className="space-y-4">{analysis?<><div className="rounded-3xl border border-violet-300/15 bg-violet-300/[.035] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-wider text-violet-300">CareerPilot analysis</p><h2 className="mt-2 text-xl font-semibold">{analysis.title}</h2><p className="mt-1 text-xs text-zinc-500">{analysis.company} · {analysis.location}</p></div><div className="text-right"><p className="text-3xl font-semibold text-violet-300">{score}</p><p className="text-[9px] uppercase tracking-wider text-zinc-700">fit signal</p></div></div><div className="mt-5 grid grid-cols-2 gap-2"><Box label="Work mode" value={analysis.workMode}/><Box label="Employment" value={analysis.employmentType}/><Box label="Experience" value={analysis.experience}/><Box label="Sponsorship" value={analysis.sponsorship}/></div></div>
 <div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Requirement coverage</p><div className="mt-3 space-y-2">{analysis.requiredSkills.map(s=>{const has=matched.includes(s);const ev=backed.includes(s);return <div key={s} className="flex items-center justify-between rounded-xl border border-white/[.06] p-3"><div className="flex items-center gap-2 text-xs"><span className={has?"text-emerald-300":"text-amber-300"}>{has?"✓":"!"}</span>{s}</div><span className="text-[10px] text-zinc-600">{ev?"Evidence-backed":has?"Skill signal":"Gap"}</span></div>})}{!analysis.requiredSkills.length&&<p className="text-xs text-zinc-600">No catalogued skills detected. Add clearer requirement text to improve the analysis.</p>}</div></div>
 <div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-600">What to do before applying</p><div className="mt-3 space-y-2">{missing.length?<Action text={"Build evidence for "+missing.slice(0,3).join(", ")}/>:<Action text="Your detected required skills are already represented in CareerPilot."/>}{backed.length<matched.length&&matched.length>0&&<Action text="Strengthen project or assessment evidence for your matched skills."/>}{analysis.preferredSkills.length>0&&<Action text={"Preferred skills detected: "+analysis.preferredSkills.join(", ")}/>}</div><button onClick={save} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-white/[.08] px-4 py-3 text-xs font-semibold hover:bg-white/[.04]">{saved?<><Check size={14}/> Saved to CareerPilot</>:<><Bookmark size={14}/> Save opportunity</>}</button></div>
 <div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-5"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Extracted details</p><div className="mt-3 space-y-2 text-xs text-zinc-500"><p><b className="text-zinc-300">Education:</b> {analysis.education}</p><p><b className="text-zinc-300">Salary:</b> {analysis.salary||"Not detected"}</p><p><b className="text-zinc-300">Preferred skills:</b> {analysis.preferredSkills.join(", ")||"None detected"}</p><p><b className="text-zinc-300">Responsibilities:</b> {analysis.responsibilities.join(" ")||"Not detected"}</p></div></div></>:<div className="rounded-3xl border border-white/[.07] bg-white/[.025] p-7"><Sparkles className="text-violet-300"/><h2 className="mt-5 text-xl font-semibold">Your job analysis will appear here</h2><p className="mt-2 text-sm leading-6 text-zinc-600">CareerPilot will turn a wall of job-description text into structured requirements, fit signals and next actions.</p></div>}</div></section>
}

function JobCard({job,score,active,saved,onSave,onClick}:{job:Job;score:number;active:boolean;saved:boolean;onSave:()=>void;onClick:()=>void}){return <div className={"rounded-3xl border p-5 "+(active?"border-violet-300/25 bg-violet-300/[.04]":"border-white/[.07] bg-white/[.025]")}><div className="flex justify-between gap-4"><button onClick={onClick} className="min-w-0 flex-1 text-left"><p className="text-xs text-zinc-600">{job.company} · {job.companyType}</p><h2 className="mt-1 text-lg font-semibold">{job.title}</h2><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-zinc-600"><span className="flex items-center gap-1"><MapPin size={12}/>{job.location}</span><span>{job.employmentType}</span><span>{job.experience}</span></div></button><div className="text-right"><p className="text-2xl font-semibold text-violet-300">{score}</p><p className="text-[9px] uppercase tracking-wider text-zinc-700">fit signal</p></div></div><div className="mt-4 flex flex-wrap gap-2">{job.skills.map(s=><span key={s} className="rounded-full border border-white/[.07] px-2.5 py-1 text-[10px] text-zinc-500">{s}</span>)}</div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-zinc-600">{job.salary||"Salary not listed"}</span><button onClick={onSave} className="rounded-xl border border-white/[.07] p-2 text-zinc-500 hover:text-white">{saved?<Bookmark size={15} fill="currentColor"/>:<Bookmark size={15}/>}</button></div></div>}
function Detail({job,score,breakdown,saved,onSave}:{job:Job;score:number;breakdown:any;saved:boolean;onSave:()=>void}){return <aside className="sticky top-6 h-fit rounded-3xl border border-violet-300/15 bg-violet-300/[.035] p-6"><div className="flex justify-between"><div><p className="text-[10px] uppercase tracking-wider text-violet-300">Opportunity analysis</p><h2 className="mt-2 text-2xl font-semibold">{job.title}</h2><p className="mt-1 text-sm text-zinc-500">{job.company}</p></div><button onClick={onSave} className="text-zinc-500">{saved?<Bookmark fill="currentColor" size={18}/>:<Bookmark size={18}/>}</button></div><div className="mt-6 grid grid-cols-2 gap-3"><Box label="Fit signal" value={score+" / 100"}/><Box label="Work mode" value={job.workMode}/><Box label="Location" value={job.location}/><Box label="Experience" value={job.experience}/></div><div className="mt-6"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Match breakdown</p><div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(breakdown).map(([k,v])=><div key={k} className="rounded-xl border border-white/[.06] p-3"><p className="text-[9px] uppercase tracking-wider text-zinc-700">{k.replace("_"," ")}</p><p className="mt-1 text-sm font-semibold text-violet-300">{String(v)}</p></div>)}</div><p className="mt-5 text-[10px] uppercase tracking-wider text-zinc-600">Requirement coverage</p><div className="mt-3 space-y-2">{job.requirements.map(r=><div key={r} className="flex items-center gap-2 rounded-xl border border-white/[.06] p-3 text-xs"><Check size={14} className="text-emerald-300"/>{r}</div>)}</div></div><div className="mt-6 rounded-2xl border border-white/[.06] p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-600">Source</p><p className="mt-2 text-xs text-zinc-400">{job.source}</p></div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-black">View opportunity <ExternalLink size={14}/></button></aside>}
function Action({text}:{text:string}){return <div className="rounded-xl border border-white/[.06] p-3 text-xs text-zinc-400">{text}</div>}
function Box({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[.06] bg-black/10 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-700">{label}</p><p className="mt-2 text-xs font-medium text-zinc-300">{value}</p></div>}
function Select({value,setValue,options}:{value:string;setValue:(v:string)=>void;options:string[][]}){return <select value={value} onChange={e=>setValue(e.target.value)} className="rounded-xl border border-white/[.07] bg-black/20 px-4 py-3 text-xs text-zinc-400 outline-none">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function Loading(){return <main className="flex min-h-screen items-center justify-center bg-[#08090d] text-zinc-500">Loading Job Intelligence...</main>}
